### ISSUE TITLE
Better example

### ISSUE THREAD

**Issue by jqn** [cinder92/react-native-bubble-menu#1]
Hi, thanks for building this component but a better example would be great. So far I haven't been able to get it to work.

![screen shot 2017-06-28 at 2 21 13 pm](https://user-images.githubusercontent.com/9710893/27658377-1122aee4-5c0d-11e7-8349-f26cfb7bf14b.png)

**Comment by cinder92** [comment]
Hey, thanks for your issue, i will post asap a better example, could you please post some of your code for better understanding?

**Comment by jqn** [comment]
Thanks here is a sample of the code. 

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import BubbleMenu from 'react-native-bubble-menu';

export default class bubleMenuEx extends Component {
  render() {
    return (
      <View style={styles.container}>
        <BubbleMenu
          items={[<Text key="1">one</Text>, <Text key="2">two</Text>]}
          openBtn={<Text>Open</Text>}
          show={true}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  button: {
    width: 30,
    height: 30,
  }
});

AppRegistry.registerComponent('bubleMenuEx', () => bubleMenuEx);
```

**Comment by jkomyno** [comment]
My PR aims to fix this issue providing a working example. I pretty much followed the blueprint of this project's GIF in the README.
https://github.com/cinder92/react-native-bubble-menu/pull/2

**Comment by cinder92** [comment]
you can check it the new doc
