### ISSUE TITLE
Unexpected behaviour with show property

### ISSUE THREAD

**Issue by jkomyno** [cinder92/react-native-bubble-menu#4]
If I pass the `show` property to true when the first render of BubbleMenu occours, I expect to see it ready and open. But it's not happening right now: instead, you have to click twice on the openBtn to see it working as expected.

**Comment by cinder92** [comment]
Hey @jkomyno i think a need to make a better doc, show property is boolean, its `true` when is open, and `false` when is closed. im going to update right now

**Comment by cinder92** [comment]
updated, check it :)

**Comment by jkomyno** [comment]
@cinder92  the show property meaning is pretty clear, I just stated that the library didn't work well if you initialize show to true. But that has been fixed in the constructor of index.JS in my PR :)

**Comment by cinder92** [comment]
@jkomyno yes, i just really reading your code, its ok, i will merge it

**Comment by cinder92** [comment]
issue fixed, i just going to close this issue. thanks @jkomyno
